#ifndef __NPC_CONFIG_H__
#define __NPC_CONFIG_H__

// #define CONFIG_MTRACE 1
// #define CONFIG_FTRACE 1
// #define CONFIG_DIFFTEST 1
// #define CONFIG_ITRACE_COND 1
// #define CONFIG_ITRACE 1
// #define CONFIG_TRACE 1
#define CONFIG_DEVICE 1
#define CONFIG_DTRACE 1
#define CONFIG_MSIZE 0x8000000
#define CONFIG_MBASE 0x80000000
#define CONFIG_PC_RESET_OFFSET 0x0
#define CONFIG_RT_CHECK 1
#define CONFIG_ISA_riscv 1
#define CONFIG_TARGET_NATIVE_ELF 1

// #define CONFIG_TRACE_START 0
// #define CONFIG_TRACE_END 10000



#define ANTO_Q 1

#endif